### ISSUE TITLE
update DT details

### ISSUE THREAD

**Issue by dw-webminister** [drachenwald/drachenwald#118]
([Dragon’s Tale: kingdom newsletter - Drachenwald (sca.org)](https://drachenwald.sca.org/offices/chronicler/kingdom-newsletter/) ) where there is a para under subscriptions:

 

Current copies can be found as PDF can be found on [the SCA Inc membership site](https://members.sca.org/apps/#NewsletterFiles/12). No membership is required to read the current PDF newsletters.

**Comment by olleolleolle** [comment]
@dw-webminister 👋 Can you clarify the change that is requested?

**Comment by olleolleolle** [comment]
cc @dw-webminister I think we have arrived, and #142 is merged.
