### ISSUE TITLE
Polderslot email wrong (possibly)

### ISSUE THREAD

**Issue by mary-wk** [drachenwald/drachenwald#12]
Path: /groups/
Oriane reports that the email address for Polderslot has a typo in it, but does not specify what the typo is. 

Looking at the polderslot info on the groups page (copied below), I agree there's an issue. The email address appears to have the wrong ending. Surely it should end in .info?

Shire of Polderslot
Region: Netherlands
Online: [http://www.polderslot.info/ ](http://www.polderslot.info/)
Seneschal: Jan van Nyenrode ([senechal@polderslot.org](mailto:senechal@polderslot.org))

**Comment by dw-webminister** [comment]
fixed in regnum
