### ISSUE TITLE
regional archery marshalls aren't showing up on website despite being in regnum

### ISSUE THREAD

**Issue by dw-webminister-deputy** [drachenwald/drachenwald#143]

**Comment by olleolleolle** [comment]
Their role_type is not "officer" (required by the template) but it is "deputy". Should the template perhaps change a little?

**Comment by hennar** [comment]
huh, you're right, the definition for the role is 'deputy' rather then 'officer'. Updated regnum definition

**Comment by olleolleolle** [comment]
https://drachenwald.sca.org/offices/archery-thrown-marshal/ this page now lists at least 1 regional officer there.

**Comment by olleolleolle** [comment]
They are now visible, fixed!

**Comment by olleolleolle** [comment]
Update: the regional officers are no longer being listed.

**Comment by olleolleolle** [comment]
UPDATE: And, they are visible, again! Thanks, @hennar, for repairs!
