### ISSUE TITLE
Incorrect page url and empty bullet on Laurel Roster page

### ISSUE THREAD

**Issue by MarcellaSCA** [drachenwald/drachenwald#147]
Path: [/posts/news/2019/03/29/crown-vigil/](https://drachenwald.sca.org/peers/laurel/laurel-roster/)

So, I opened this because there's a persistent empty bullet under 'Online presence' that I don't know how to remove.

The other issue is that when I opened GitHub to log that, the path was to a news post from 2019 rather than to the Laurel roster, which seems odd.

**Comment by olleolleolle** [comment]
Thanks for the report!

(https://github.com/drachenwald/drachenwald/issues/71 notes the "wrong Path being offered to the Issue".)
