### ISSUE TITLE
Corrupted files for heraldry submission

### ISSUE THREAD

**Issue by TestTimothy** [drachenwald/drachenwald#157]
https://drachenwald.sca.org/offices/herald/submittingnamesheraldry/ links to four PDFs (name, device, and badge forms for individuals and groups) and two PNGs (blank badge and blank device).

The PDFs open successfully in Firefox and Chromium, but when downloaded they do not open in either Evince (Document Reader) or GIMP. Two (badge.pdf and device.pdf) show the error message "Failed to read the document catalog" while the other two show the error message "PDF document is damaged". The same error message shows in both Evince and GIMP.

The two PNGs fail to open anywhere. Chromium just shows a generic failed image symbol, while Firefox says that the image cannot be displayed because it contains errors. Downloading the image and opening it with Eye of Gnome produces a more useful error message: "Fatal error reading PNG image file: PNG file corrupted by ASCII conversion". (Meanwhile, GIMP says "File corrupted?")

Any corruption in these six files is not an artefact of the web build process: the files in the source code are identical to those downloaded from the website.

**Comment by olleolleolle** [comment]
I peeked at the PNG file with https://github.com/Pourliver/PNG-Fixer/blob/master/png_fixer.py

```
olle.jonsson@Olles-Laptop drachenwald % python3 png_fixer.py offices/herald/files/blank-badge.png offices/herald/files/blank-badge-output.png
Validating magicbytes...
Invalid
Expected : b'\x89PNG\r\n\x1a\n'
Result   : b'\x89PNG\n\x1a\n\x00'
Repairing magicbytes
Retrying...
Validating magicbytes...
Valid
-----------------------
Parsing header : b'HDR\x00' at offset 12
CRC : 0
Type is invalid
Repairing chunk type
Current type : b'HDR\x00'
Possible choices : [b'IHDR', b'PLTE', b'IDAT', b'IEND', b'bKGD', b'cHRM', b'dSIG', b'eXIf', b'gAMA', b'hIST', b'iCCP', b'iTXt', b'pHYs', b'sBIT', b'sPLT', b'sRGB', b'sTER', b'tEXt', b'tIME', b'tRNS', b'zTXt']
```

So, something happened to the file at some point. I will take a look at the .gitattributes, which has a note not to work on the content of *.png files. Perhaps it got screwy then?
