### ISSUE TITLE
Kingdom Equestrian Officer Details Missing

### ISSUE THREAD

**Issue by jpgsawyer** [drachenwald/drachenwald#163]
Hi All,
Can I please be listed as the Kingdom Equestrian Marshal on the website. I used to be and I don't quite know why it has dropped off as I haven't stopped being the marshal.

There is a stub for the page https://drachenwald.sca.org/offices/equestrian-marshal/ but it is blank.

Please use the following details

SCA Name: Thomas Flamanc of Kelsale
Legal Name: John Sawyer
Contact Details: jpgsawyer@gmail.com

Many thanks.

John

**Comment by jpgsawyer** [comment]
Sorry just found the link for adding my details using the google form. I have done that now. Thanks

**Comment by olleolleolle** [comment]
@jpgsawyer That is super, and thank you for your service!

**Comment by jpgsawyer** [comment]
Yes I think it will.
