### ISSUE TITLE
hamburger bar (menu) not visible on phone

### ISSUE THREAD

**Issue by vcalukovic** [drachenwald/drachenwald#25]
![Screenshot_20221202-193427](https://user-images.githubusercontent.com/81240346/205362962-b470a1f7-f311-42e7-a1d0-0a8faa07ec9e.jpg)
Path: /posts/news/2019/03/29/crown-vigil/

Only after pressing where you'd expect it to be does it pop out, as it is then focussed
![Screenshot_20221202-193434](https://user-images.githubusercontent.com/81240346/205363124-c42e57ac-2d8d-4ff6-aedd-62227b603f83.jpg)
![Screenshot_20221202-193438](https://user-images.githubusercontent.com/81240346/205363144-c8afe29d-4143-488b-b128-bb241631055e.jpg)

Pressing again elsewhere leads to unfocus, making it disappear again - even though, when focused, there seems to be a colour difference

**Comment by dw-webminister-deputy** [comment]
Cannot replicate on Android with either Chrome, Firefox or Opera. 
Cannot replicate on iOS/iPadOS in Safari.  

All latest browser versions.
