### ISSUE TITLE
"Edit this page on GitHub" link seems to all point to a single page

### ISSUE THREAD

**Issue by olleolleolle** [drachenwald/drachenwald#71]
I "edited the page", and was referred to a very different article (something about a 2019 crown tourney `/posts/news/2019/03/29/crown-vigil/`).

Observation: I noticed that someone else referred to that page in #67 

Could something be up?

The https://github.com/drachenwald/drachenwald/blob/97f826d465cb0290bb785e100194bc97c94ad81c/_includes/footer.html#L20 looks alright: `href="{{site.github.repository_url}}/blob/main/{{ page.path }}` 

## Clues

- That URL above, it matches the first Markdown file in `_posts/`

**Comment by mollydot** [comment]
I got the same just now.

**Comment by mathleuch** [comment]
Same
