### ISSUE TITLE
Chatelaine: The link to Yahoo Groups can safely be removed

### ISSUE THREAD

**Issue by olleolleolle** [drachenwald/drachenwald#78]
References to Yahoo Groups are now removable - not possible to access any of its content any longer.

Example of the last visible Archive.org page for one of the Groups: just a front page, all messages locked in the group, and not archived.
https://web.archive.org/web/20070906145247/http://tech.groups.yahoo.com/group/SCAteach/

### Screenshot 
<img width="1776" alt="bild" src="https://github.com/drachenwald/drachenwald/assets/211/b2f4a309-2bbe-4c79-87ff-2d59d16cda6c">

**Comment by dw-webminister** [comment]
removed references to chatelaine and archery yahoo groups. these were the last remaining on the site.
